---
title: "Eating-disorder psychopathology in female athletes and non-athletes: A meta-analysis"
type: "article"
author: "Danielle A. N. Chapa, Sarah N. Johnson, Brianne N. Richson, Kayla Bjorlie, Ying Q. Won, Sarah V. Nelson, Joseph Ayres, Daiil Jun, Kelsie T. Forbush, Kara A. Christensen, Victoria L. Perko"
year: "2022"
publication: "International Journal of Eating Disorders"
doi: "https://doi.org/10.1002/eat.23748"
materials: "https://onlinelibrary.wiley.com/doi/10.1002/eat.23748"
toc: false
---

## Citation (APA 7)

> Chapa, D. A. N., Johnson, S. N., Richson, B. N., Bjorlie, K., Won, Y. Q., Nelson, S. V., Ayres, J., Jun, D., Forbush, K. T., Christensen, K. A., & Perko, V. L. (2022). Eating-disorder psychopathology in female athletes and non-athletes: A meta-analysis. *International Journal of Eating Disorders*, 55(7), 861–885. https://doi.org/10.1002/eat.23748.


## Abstract

**Objective**

There is ongoing discussion about whether sports participation is a risk or protective factor for eating disorders (EDs). Research is mixed, with some studies suggesting that athletes have higher mean levels of ED psychopathology compared to nonathletes, while other studies suggest the opposite effect or no differences. The purpose of the current meta-analysis was to identify whether female athletes reported higher mean levels of ED psychopathology compared to nonathletes.

**Method**

Following PRISMA guidelines, we identified 56 studies that reported ED psychopathology for female athletes and nonathletes. A three-level random-effects model of between- and within-study variance was completed for the following outcome variables: overall ED psychopathology, body dissatisfaction, drive for thinness, restricting, and loss-of-control eating.

**Results**

Athletes reported lower levels of body dissatisfaction compared to nonathletes (g = −.21, p < .0001). Athletes and nonathletes reported similar levels of overall ED psychopathology, drive for thinness, restricting, and loss-of-control eating on average. Sport type significantly moderated standardized mean difference effect sizes of ED psychopathology in athletes versus nonathletes. Effect sizes comparing levels of drive for thinness, restricting, and loss-of-control eating in athletes versus nonathletes were larger for studies with athletes participating in aesthetic/lean sports compared to nonaesthetic/nonlean sports.

**Discussion**

Findings from this meta-analysis could inform future ED prevention and treatment in female athletes by providing further evidence that athletes in aesthetic/lean sports may report higher levels of ED psychopathology. Participating in nonaesthetic/nonlean sports may be a protective factor for experiencing less body dissatisfaction.

**Public Significance Statement**

The current meta-analysis summarized findings from 56 studies that assessed levels of disordered eating, body dissatisfaction, dietary restricting, and loss-of-control eating in female athletes and nonathletes. Athletes reported lower levels of body dissatisfaction compared to nonathletes, highlighting that participation in sport could have some protective factors.

Athletes participating in sports that require weight categories (e.g., judo) and sports that emphasize thinness/leanness (e.g., gymnastics and distance running) had higher levels of disordered eating relative to athletes participating in other types of sports that do not emphasize thinness/leanness (e.g., volleyball and basketball).