---
title: "US tobacco companies selectively disseminated hyper-palatable foods into the US food system: Empirical evidence and current implications"
type: "article"
author: "Tera L. Fazzino, Daiil Jun, Lynn Chollet-Hinton, Kayla Bjorlie"
year: "2023"
publication: "Addiction"
doi: "https://doi.org/10.1111/add.16332"
materials: "https://onlinelibrary.wiley.com/doi/10.1111/add.16332"
toc: false
---

## Citation (APA 7)

> Fazzino, T. L., Jun, D., Chollet‐Hinton, L., & Bjorlie, K. (2023). US tobacco companies selectively disseminated hyper‐palatable foods into the US food system: Empirical evidence and current implications. *Addiction*.

## Abstract

**Background and aims**

US tobacco companies owned leading US food companies from 1980 to 2001. We measured whether hyper-palatable foods (HPF) were disproportionately developed in tobacco-owned food companies, resulting in substantial tobacco-related influence on the US food system.

**Design** 

The study involved a review of primary industry documents to identify food brands that were tobacco company-owned. Data sets from the US Department of Agriculture were integrated to facilitate longitudinal analyses estimating the degree to which foods were formulated to be hyper-palatable, based on tobacco ownership.

**Setting and cases** 

United States Department of Agriculture data sets were used to identify HPF foods that were (n = 105) and were not (n = 587) owned by US tobacco companies from 1988 to 2001.

**Measurements**

A standardized definition from Fazzino et al. (2019) was used to identify HPF. HPF items were identified overall and by HPF group: fat and sodium HPF, fat and sugar HPF and carbohydrates and sodium HPF.

**Findings**

Tobacco-owned foods were 29% more likely to be classified as fat and sodium HPF and 80% more likely to be classified as carbohydrate and sodium HPF than foods that were not tobacco-owned between 1988 and 2001 (P-values = 0.005--0.009). The availability of fat and sodium HPF (\> 57%) and carbohydrate and sodium HPF (\> 17%) was high in 2018 regardless of prior tobacco-ownership status, suggesting widespread saturation into the food system.

**Conclusions**

Tobacco companies appear to have selectively disseminated hyper-palatable foods into the US food system between 1988 and 2001.
